<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ $title ?? 'BloodBankSystem' }} | Blood Donor Platform</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<style>
:root{--red:#d92d3d;--red-dark:#b42333;--navy:#172033;--muted:#667085;--bg:#f6f8fc;--border:#eaecf0}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--navy);font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif}.card{border:0;border-radius:18px;box-shadow:0 8px 28px rgba(16,24,40,.06)}.navbar{box-shadow:0 1px 8px rgba(16,24,40,.08)}.brand{font-weight:800;color:var(--red)!important}.lb-nav{padding:10px 0}.lb-brand{display:flex;align-items:center;gap:10px;color:#182230!important}.lb-brand-icon{width:46px;height:46px;border-radius:14px;background:#e52b31;color:white;display:grid;place-items:center;font-size:2rem}.lb-brand b{display:block;font-size:1.25rem;line-height:1}.lb-brand small{display:block;color:#e52b31;font-size:.72rem;margin-top:4px}.lb-nav .nav-link{font-weight:650;color:#526078;border-radius:10px;padding:10px 14px}.lb-nav .nav-link.active,.lb-nav .nav-link:hover{background:#fff0f2;color:#e52b31}.badge{font-weight:600}.table>:not(caption)>*>*{padding:14px}
.donor-app{min-height:calc(100vh - 64px);display:flex}.donor-sidebar{width:248px;flex:0 0 248px;background:#111827;color:#d1d5db;min-height:calc(100vh - 64px);padding:22px 14px;position:sticky;top:64px}.side-brand{display:flex;align-items:center;gap:10px;color:#fff;text-decoration:none;font-weight:800;font-size:1.05rem;padding:10px 12px 20px}.brand-dot{width:34px;height:34px;border-radius:10px;background:var(--red);display:grid;place-items:center}.side-label{font-size:.7rem;text-transform:uppercase;letter-spacing:.08em;color:#98a2b3;padding:10px 12px 6px}.side-link{display:flex;align-items:center;gap:11px;color:#cbd5e1;text-decoration:none;padding:11px 12px;border-radius:11px;margin:4px 0;font-size:.94rem;transition:.2s}.side-link:hover,.side-link.active{background:#2b3445;color:#fff}.side-link.active{box-shadow:inset 3px 0 0 var(--red)}.side-icon{width:22px;text-align:center}.side-divider{height:1px;background:#263142;margin:18px 10px}.donor-main{flex:1;min-width:0;padding:30px 34px 45px}.donor-topbar{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:28px}.donor-greeting h1{font-size:1.9rem;font-weight:800;margin:0 0 5px}.donor-greeting p{color:var(--muted);margin:0}.donor-profile-chip{display:flex;align-items:center;gap:10px;background:#fff;border:1px solid var(--border);padding:7px 10px 7px 7px;border-radius:999px;box-shadow:0 4px 15px rgba(16,24,40,.05)}.avatar{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;background:#fde7ea;color:var(--red);font-weight:800}.profile-name{font-size:.9rem;font-weight:700;line-height:1.1}.profile-role{font-size:.72rem;color:var(--muted)}.profile-caret{color:#98a2b3}
.stat-card{height:100%;padding:20px}.stat-icon{width:44px;height:44px;border-radius:12px;background:#fff0f2;color:var(--red);display:grid;place-items:center;font-size:1.2rem;margin-bottom:16px}.stat-label{color:var(--muted);font-size:.86rem;margin-bottom:5px}.stat-value{font-size:1.65rem;font-weight:800;line-height:1.1}.stat-sub{color:#98a2b3;font-size:.76rem;margin-top:6px}.blood-pill{display:inline-flex;align-items:center;justify-content:center;background:var(--red);color:#fff;border-radius:10px;padding:5px 10px;font-weight:800}.quick-title,.section-title{font-size:1.1rem;font-weight:800;margin:0}.quick-card{display:flex;align-items:center;gap:14px;text-decoration:none;color:inherit;padding:18px;background:#fff;border-radius:16px;border:1px solid var(--border);box-shadow:0 5px 18px rgba(16,24,40,.04);height:100%;transition:.2s}.quick-card:hover{transform:translateY(-2px);box-shadow:0 10px 25px rgba(16,24,40,.08);color:inherit}.quick-icon{width:44px;height:44px;border-radius:12px;background:#fff0f2;display:grid;place-items:center;font-size:1.2rem}.quick-title-text{font-weight:750;font-size:.93rem}.quick-sub{font-size:.75rem;color:var(--muted);margin-top:2px}.section-card{padding:22px;height:100%}.section-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:15px}.empty-state{text-align:center;padding:30px 15px}.empty-icon{width:54px;height:54px;border-radius:16px;background:#f2f4f7;display:grid;place-items:center;margin:0 auto 12px;font-size:1.35rem}.empty-title{font-weight:750;margin-bottom:5px}.empty-text{font-size:.83rem;color:var(--muted);margin-bottom:16px}.donation-banner{background:linear-gradient(135deg,#fff0f2,#fff);border:1px solid #fbd5da;border-radius:18px;padding:25px 28px;display:flex;align-items:center;justify-content:space-between;gap:20px}.donation-banner h4{font-weight:800;margin:0 0 6px}.donation-banner p{color:var(--muted);margin:0;font-size:.88rem}.btn-lb{background:var(--red);border-color:var(--red);color:#fff;font-weight:700;border-radius:10px}.btn-lb:hover{background:var(--red-dark);border-color:var(--red-dark);color:#fff}.btn-outline-lb{border-color:#f0a5ad;color:var(--red);font-weight:700;border-radius:10px}.btn-outline-lb:hover{background:#fff0f2;color:var(--red)}
@media(max-width:991px){.donor-sidebar{width:82px;flex-basis:82px;padding:18px 9px}.donor-sidebar .side-brand span:last-child,.side-link span:not(.side-icon),.side-label{display:none}.side-link{justify-content:center;padding:12px}.donor-main{padding:25px 20px 40px}}@media(max-width:767px){.donor-sidebar{display:none}.donor-main{padding:22px 15px 35px}.donor-topbar{align-items:flex-start}.donor-greeting h1{font-size:1.5rem}.donor-profile-chip{display:none}.donation-banner{align-items:flex-start;flex-direction:column}}
</style>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-white lb-nav sticky-top"><div class="container px-3"><a class="navbar-brand lb-brand" href="{{ route('home') }}"><span class="lb-brand-icon">♢</span><span><b>BloodBankSystem</b><small>Donate Blood, Save Lives</small></span></a><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNav">☰</button><div class="collapse navbar-collapse" id="mainNav"><ul class="navbar-nav mx-auto gap-lg-2"><li class="nav-item"><a class="nav-link {{ request()->routeIs('home') ? 'active' : '' }}" href="{{ route('home') }}">Home</a></li><li class="nav-item"><a class="nav-link {{ request()->routeIs('donors.index') ? 'active' : '' }}" href="{{ route('donors.index') }}">Find Donors</a></li><li class="nav-item"><a class="nav-link {{ request()->routeIs('banks.index') ? 'active' : '' }}" href="{{ route('banks.index') }}">Blood Banks</a></li><li class="nav-item"><a class="nav-link {{ request()->routeIs('blog.index') ? 'active' : '' }}" href="{{ route('blog.index') }}">Blog</a></li><li class="nav-item"><a class="nav-link {{ request()->routeIs('about') ? 'active' : '' }}" href="{{ route('about') }}">About</a></li></ul><div class="d-flex gap-2"><a class="btn btn-link text-decoration-none text-dark fw-semibold" href="{{ route('admin.index') }}">Sign in</a><a class="btn btn-danger px-4 fw-bold" href="{{ route('admin.index') }}#donors">♡ Become a Donor</a></div></div></div></nav>
<div>@if(session('success'))<div class="container"><div class="alert alert-success mt-3">{{ session('success') }}</div></div>@endif @if($errors->any())<div class="container"><div class="alert alert-danger mt-3"><ul class="mb-0">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div></div>@endif @yield('content')</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body></html>
